# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(811, 854)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.port_3 = QtWidgets.QFrame(self.centralwidget)
        self.port_3.setGeometry(QtCore.QRect(10, 10, 161, 71))
        self.port_3.setStyleSheet("")
        self.port_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.port_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.port_3.setMidLineWidth(1)
        self.port_3.setObjectName("port_3")
        self.baud = QtWidgets.QComboBox(self.port_3)
        self.baud.setGeometry(QtCore.QRect(50, 40, 101, 20))
        self.baud.setObjectName("baud")
        self.baud_label = QtWidgets.QLabel(self.port_3)
        self.baud_label.setGeometry(QtCore.QRect(10, 40, 31, 16))
        self.baud_label.setObjectName("baud_label")
        self.port_label = QtWidgets.QLabel(self.port_3)
        self.port_label.setGeometry(QtCore.QRect(12, 12, 31, 16))
        self.port_label.setObjectName("port_label")
        self.port = QtWidgets.QComboBox(self.port_3)
        self.port.setGeometry(QtCore.QRect(50, 10, 101, 20))
        self.port.setObjectName("port")
        self.step_1 = QtWidgets.QLabel(self.centralwidget)
        self.step_1.setGeometry(QtCore.QRect(180, 20, 271, 21))
        self.step_1.setObjectName("step_1")
        self.step_2 = QtWidgets.QLabel(self.centralwidget)
        self.step_2.setGeometry(QtCore.QRect(180, 50, 271, 21))
        self.step_2.setObjectName("step_2")
        self.settings = QtWidgets.QFrame(self.centralwidget)
        self.settings.setGeometry(QtCore.QRect(10, 90, 791, 721))
        self.settings.setStyleSheet("")
        self.settings.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.settings.setFrameShadow(QtWidgets.QFrame.Plain)
        self.settings.setMidLineWidth(1)
        self.settings.setObjectName("settings")
        self.load_settings = QtWidgets.QCommandLinkButton(self.settings)
        self.load_settings.setGeometry(QtCore.QRect(100, 10, 151, 41))
        self.load_settings.setObjectName("load_settings")
        self.save_settings = QtWidgets.QCommandLinkButton(self.settings)
        self.save_settings.setEnabled(False)
        self.save_settings.setGeometry(QtCore.QRect(320, 10, 141, 41))
        self.save_settings.setObjectName("save_settings")
        self.reset_to_defaults = QtWidgets.QCommandLinkButton(self.settings)
        self.reset_to_defaults.setEnabled(False)
        self.reset_to_defaults.setGeometry(QtCore.QRect(540, 10, 161, 41))
        self.reset_to_defaults.setObjectName("reset_to_defaults")
        self.copy_req_to_remote = QtWidgets.QCommandLinkButton(self.settings)
        self.copy_req_to_remote.setEnabled(False)
        self.copy_req_to_remote.setGeometry(QtCore.QRect(90, 660, 221, 41))
        self.copy_req_to_remote.setObjectName("copy_req_to_remote")
        self.local = QtWidgets.QFrame(self.settings)
        self.local.setEnabled(False)
        self.local.setGeometry(QtCore.QRect(10, 60, 381, 581))
        self.local.setStyleSheet("")
        self.local.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.local.setFrameShadow(QtWidgets.QFrame.Plain)
        self.local.setMidLineWidth(1)
        self.local.setObjectName("local")
        self.version_label = QtWidgets.QLabel(self.local)
        self.version_label.setGeometry(QtCore.QRect(10, 40, 41, 16))
        self.version_label.setObjectName("version_label")
        self.radio_version = QtWidgets.QLabel(self.local)
        self.radio_version.setGeometry(QtCore.QRect(50, 40, 141, 16))
        self.radio_version.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.radio_version.setText("")
        self.radio_version.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.radio_version.setObjectName("radio_version")
        self.board_freq = QtWidgets.QLabel(self.local)
        self.board_freq.setGeometry(QtCore.QRect(190, 40, 101, 16))
        self.board_freq.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.board_freq.setText("")
        self.board_freq.setObjectName("board_freq")
        self.device = QtWidgets.QLabel(self.local)
        self.device.setGeometry(QtCore.QRect(300, 40, 71, 51))
        self.device.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.device.setText("")
        self.device.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.device.setObjectName("device")
        self.rssi = QtWidgets.QLabel(self.local)
        self.rssi.setGeometry(QtCore.QRect(50, 60, 241, 31))
        self.rssi.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.rssi.setText("")
        self.rssi.setWordWrap(True)
        self.rssi.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.rssi.setObjectName("rssi")
        self.rssi_label = QtWidgets.QLabel(self.local)
        self.rssi_label.setGeometry(QtCore.QRect(10, 65, 41, 21))
        self.rssi_label.setObjectName("rssi_label")
        self.format = QtWidgets.QLabel(self.local)
        self.format.setGeometry(QtCore.QRect(80, 100, 101, 20))
        self.format.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.format.setText("")
        self.format.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.format.setObjectName("format")
        self.format_label = QtWidgets.QLabel(self.local)
        self.format_label.setGeometry(QtCore.QRect(10, 100, 41, 16))
        self.format_label.setObjectName("format_label")
        self.baud_setting_label = QtWidgets.QLabel(self.local)
        self.baud_setting_label.setGeometry(QtCore.QRect(10, 130, 41, 16))
        self.baud_setting_label.setObjectName("baud_setting_label")
        self.baud_setting = QtWidgets.QComboBox(self.local)
        self.baud_setting.setGeometry(QtCore.QRect(80, 130, 101, 21))
        self.baud_setting.setObjectName("baud_setting")
        self.air_speed = QtWidgets.QComboBox(self.local)
        self.air_speed.setGeometry(QtCore.QRect(80, 160, 101, 21))
        self.air_speed.setObjectName("air_speed")
        self.air_speed_label = QtWidgets.QLabel(self.local)
        self.air_speed_label.setGeometry(QtCore.QRect(10, 160, 51, 16))
        self.air_speed_label.setObjectName("air_speed_label")
        self.net_id = QtWidgets.QComboBox(self.local)
        self.net_id.setGeometry(QtCore.QRect(80, 190, 101, 21))
        self.net_id.setObjectName("net_id")
        self.net_id_label = QtWidgets.QLabel(self.local)
        self.net_id_label.setGeometry(QtCore.QRect(10, 190, 51, 16))
        self.net_id_label.setObjectName("net_id_label")
        self.tx_pwr = QtWidgets.QComboBox(self.local)
        self.tx_pwr.setGeometry(QtCore.QRect(80, 220, 101, 21))
        self.tx_pwr.setObjectName("tx_pwr")
        self.tx_pwr_label = QtWidgets.QLabel(self.local)
        self.tx_pwr_label.setGeometry(QtCore.QRect(10, 220, 51, 16))
        self.tx_pwr_label.setObjectName("tx_pwr_label")
        self.ecc_label = QtWidgets.QLabel(self.local)
        self.ecc_label.setGeometry(QtCore.QRect(10, 250, 61, 16))
        self.ecc_label.setObjectName("ecc_label")
        self.ecc = QtWidgets.QCheckBox(self.local)
        self.ecc.setGeometry(QtCore.QRect(100, 250, 16, 20))
        self.ecc.setText("")
        self.ecc.setObjectName("ecc")
        self.mavlink_label = QtWidgets.QLabel(self.local)
        self.mavlink_label.setGeometry(QtCore.QRect(10, 280, 51, 16))
        self.mavlink_label.setObjectName("mavlink_label")
        self.mavlink = QtWidgets.QComboBox(self.local)
        self.mavlink.setGeometry(QtCore.QRect(80, 280, 101, 21))
        self.mavlink.setObjectName("mavlink")
        self.op_resend_label = QtWidgets.QLabel(self.local)
        self.op_resend_label.setGeometry(QtCore.QRect(10, 310, 61, 16))
        self.op_resend_label.setObjectName("op_resend_label")
        self.op_resend = QtWidgets.QCheckBox(self.local)
        self.op_resend.setGeometry(QtCore.QRect(100, 310, 16, 20))
        self.op_resend.setText("")
        self.op_resend.setObjectName("op_resend")
        self.gpi1_1rcin_label = QtWidgets.QLabel(self.local)
        self.gpi1_1rcin_label.setGeometry(QtCore.QRect(10, 370, 71, 16))
        self.gpi1_1rcin_label.setObjectName("gpi1_1rcin_label")
        self.gpo1_1rcout_label = QtWidgets.QLabel(self.local)
        self.gpo1_1rcout_label.setGeometry(QtCore.QRect(10, 400, 81, 16))
        self.gpo1_1rcout_label.setObjectName("gpo1_1rcout_label")
        self.min_freq = QtWidgets.QComboBox(self.local)
        self.min_freq.setGeometry(QtCore.QRect(270, 100, 101, 21))
        self.min_freq.setObjectName("min_freq")
        self.min_freq_label = QtWidgets.QLabel(self.local)
        self.min_freq_label.setGeometry(QtCore.QRect(200, 100, 51, 16))
        self.min_freq_label.setObjectName("min_freq_label")
        self.max_freq_label = QtWidgets.QLabel(self.local)
        self.max_freq_label.setGeometry(QtCore.QRect(200, 130, 51, 16))
        self.max_freq_label.setObjectName("max_freq_label")
        self.max_freq = QtWidgets.QComboBox(self.local)
        self.max_freq.setGeometry(QtCore.QRect(270, 130, 101, 21))
        self.max_freq.setObjectName("max_freq")
        self.num_channels_label = QtWidgets.QLabel(self.local)
        self.num_channels_label.setGeometry(QtCore.QRect(200, 160, 61, 16))
        self.num_channels_label.setObjectName("num_channels_label")
        self.num_channels = QtWidgets.QComboBox(self.local)
        self.num_channels.setGeometry(QtCore.QRect(270, 160, 101, 21))
        self.num_channels.setObjectName("num_channels")
        self.duty_cycle_label = QtWidgets.QLabel(self.local)
        self.duty_cycle_label.setGeometry(QtCore.QRect(200, 190, 61, 16))
        self.duty_cycle_label.setObjectName("duty_cycle_label")
        self.duty_cycle = QtWidgets.QComboBox(self.local)
        self.duty_cycle.setGeometry(QtCore.QRect(270, 190, 101, 21))
        self.duty_cycle.setObjectName("duty_cycle")
        self.lbt_rssi_label = QtWidgets.QLabel(self.local)
        self.lbt_rssi_label.setGeometry(QtCore.QRect(200, 220, 61, 16))
        self.lbt_rssi_label.setObjectName("lbt_rssi_label")
        self.lbt_rssi = QtWidgets.QComboBox(self.local)
        self.lbt_rssi.setGeometry(QtCore.QRect(270, 220, 101, 21))
        self.lbt_rssi.setObjectName("lbt_rssi")
        self.max_window_label = QtWidgets.QLabel(self.local)
        self.max_window_label.setGeometry(QtCore.QRect(200, 280, 71, 16))
        self.max_window_label.setObjectName("max_window_label")
        self.max_window = QtWidgets.QComboBox(self.local)
        self.max_window.setGeometry(QtCore.QRect(270, 280, 101, 21))
        self.max_window.setObjectName("max_window")
        self.flow_control_label = QtWidgets.QLabel(self.local)
        self.flow_control_label.setGeometry(QtCore.QRect(200, 250, 51, 16))
        self.flow_control_label.setObjectName("flow_control_label")
        self.flow_control = QtWidgets.QCheckBox(self.local)
        self.flow_control.setGeometry(QtCore.QRect(290, 250, 16, 20))
        self.flow_control.setText("")
        self.flow_control.setObjectName("flow_control")
        self.aes_encrypt_label = QtWidgets.QLabel(self.local)
        self.aes_encrypt_label.setGeometry(QtCore.QRect(200, 310, 81, 16))
        self.aes_encrypt_label.setObjectName("aes_encrypt_label")
        self.aes_encrypt = QtWidgets.QCheckBox(self.local)
        self.aes_encrypt.setGeometry(QtCore.QRect(290, 310, 16, 20))
        self.aes_encrypt.setText("")
        self.aes_encrypt.setObjectName("aes_encrypt")
        self.aes_key = QtWidgets.QLabel(self.local)
        self.aes_key.setGeometry(QtCore.QRect(160, 350, 211, 21))
        self.aes_key.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.aes_key.setText("")
        self.aes_key.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextEditable|QtCore.Qt.TextSelectableByMouse)
        self.aes_key.setObjectName("aes_key")
        self.aes_key_label = QtWidgets.QLabel(self.local)
        self.aes_key_label.setGeometry(QtCore.QRect(160, 330, 51, 16))
        self.aes_key_label.setObjectName("aes_key_label")
        self.standard_mavlink = QtWidgets.QPushButton(self.local)
        self.standard_mavlink.setGeometry(QtCore.QRect(160, 380, 101, 23))
        self.standard_mavlink.setObjectName("standard_mavlink")
        self.low_latency = QtWidgets.QPushButton(self.local)
        self.low_latency.setGeometry(QtCore.QRect(270, 380, 101, 23))
        self.low_latency.setObjectName("low_latency")
        self.gpo1_1sbusin_label = QtWidgets.QLabel(self.local)
        self.gpo1_1sbusin_label.setGeometry(QtCore.QRect(10, 430, 81, 16))
        self.gpo1_1sbusin_label.setObjectName("gpo1_1sbusin_label")
        self.gpo1_3statled_label = QtWidgets.QLabel(self.local)
        self.gpo1_3statled_label.setGeometry(QtCore.QRect(10, 490, 81, 16))
        self.gpo1_3statled_label.setObjectName("gpo1_3statled_label")
        self.ant_mode_label = QtWidgets.QLabel(self.local)
        self.ant_mode_label.setGeometry(QtCore.QRect(200, 420, 71, 16))
        self.ant_mode_label.setObjectName("ant_mode_label")
        self.ant_mode = QtWidgets.QComboBox(self.local)
        self.ant_mode.setGeometry(QtCore.QRect(270, 420, 101, 21))
        self.ant_mode.setObjectName("ant_mode")
        self.gpi1_1rcin = QtWidgets.QRadioButton(self.local)
        self.gpi1_1rcin.setGeometry(QtCore.QRect(100, 370, 16, 17))
        self.gpi1_1rcin.setText("")
        self.gpi1_1rcin.setObjectName("gpi1_1rcin")
        self.buttonGroup_remote = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_remote.setObjectName("buttonGroup_remote")
        self.buttonGroup_remote.addButton(self.gpi1_1rcin)
        self.gpo1_1rcout = QtWidgets.QRadioButton(self.local)
        self.gpo1_1rcout.setGeometry(QtCore.QRect(100, 400, 16, 17))
        self.gpo1_1rcout.setText("")
        self.gpo1_1rcout.setObjectName("gpo1_1rcout")
        self.buttonGroup_remote.addButton(self.gpo1_1rcout)
        self.gpo1_1sbusin = QtWidgets.QRadioButton(self.local)
        self.gpo1_1sbusin.setGeometry(QtCore.QRect(100, 430, 16, 17))
        self.gpo1_1sbusin.setText("")
        self.gpo1_1sbusin.setObjectName("gpo1_1sbusin")
        self.buttonGroup_remote.addButton(self.gpo1_1sbusin)
        self.gpo1_1sbusout = QtWidgets.QRadioButton(self.local)
        self.gpo1_1sbusout.setGeometry(QtCore.QRect(100, 460, 16, 17))
        self.gpo1_1sbusout.setText("")
        self.gpo1_1sbusout.setObjectName("gpo1_1sbusout")
        self.buttonGroup_remote.addButton(self.gpo1_1sbusout)
        self.gpo1_3statled = QtWidgets.QRadioButton(self.local)
        self.gpo1_3statled.setGeometry(QtCore.QRect(100, 490, 16, 17))
        self.gpo1_3statled.setText("")
        self.gpo1_3statled.setObjectName("gpo1_3statled")
        self.buttonGroup_remote.addButton(self.gpo1_3statled)
        self.gpo1_1sbusout_label = QtWidgets.QLabel(self.local)
        self.gpo1_1sbusout_label.setGeometry(QtCore.QRect(10, 460, 91, 16))
        self.gpo1_1sbusout_label.setObjectName("gpo1_1sbusout_label")
        self.gpio_1_0_nromal_label = QtWidgets.QLabel(self.local)
        self.gpio_1_0_nromal_label.setGeometry(QtCore.QRect(10, 520, 91, 16))
        self.gpio_1_0_nromal_label.setObjectName("gpio_1_0_nromal_label")
        self.gpio_1_0_nromal = QtWidgets.QRadioButton(self.local)
        self.gpio_1_0_nromal.setGeometry(QtCore.QRect(100, 520, 16, 17))
        self.gpio_1_0_nromal.setText("")
        self.gpio_1_0_nromal.setChecked(True)
        self.gpio_1_0_nromal.setObjectName("gpio_1_0_nromal")
        self.buttonGroup_4 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_4.setObjectName("buttonGroup_4")
        self.buttonGroup_4.addButton(self.gpio_1_0_nromal)
        self.gpio_1_1_normal = QtWidgets.QRadioButton(self.local)
        self.gpio_1_1_normal.setGeometry(QtCore.QRect(100, 340, 16, 17))
        self.gpio_1_1_normal.setText("")
        self.gpio_1_1_normal.setChecked(True)
        self.gpio_1_1_normal.setObjectName("gpio_1_1_normal")
        self.buttonGroup_remote.addButton(self.gpio_1_1_normal)
        self.gpio_1_1_normal_label = QtWidgets.QLabel(self.local)
        self.gpio_1_1_normal_label.setGeometry(QtCore.QRect(10, 340, 91, 16))
        self.gpio_1_1_normal_label.setObjectName("gpio_1_1_normal_label")
        self.gpo1_0_txen485_label = QtWidgets.QLabel(self.local)
        self.gpo1_0_txen485_label.setGeometry(QtCore.QRect(10, 550, 81, 16))
        self.gpo1_0_txen485_label.setObjectName("gpo1_0_txen485_label")
        self.gpo1_0_txen485 = QtWidgets.QRadioButton(self.local)
        self.gpo1_0_txen485.setGeometry(QtCore.QRect(100, 550, 16, 17))
        self.gpo1_0_txen485.setText("")
        self.gpo1_0_txen485.setObjectName("gpo1_0_txen485")
        self.buttonGroup_4.addButton(self.gpo1_0_txen485)
        self.rate_and_freq_bands = QtWidgets.QComboBox(self.local)
        self.rate_and_freq_bands.setGeometry(QtCore.QRect(270, 450, 101, 21))
        self.rate_and_freq_bands.setObjectName("rate_and_freq_bands")
        self.rate_and_freq_bands_label = QtWidgets.QLabel(self.local)
        self.rate_and_freq_bands_label.setGeometry(QtCore.QRect(170, 450, 101, 20))
        self.rate_and_freq_bands_label.setObjectName("rate_and_freq_bands_label")
        self.target_rssi = QtWidgets.QComboBox(self.local)
        self.target_rssi.setGeometry(QtCore.QRect(270, 480, 101, 21))
        self.target_rssi.setObjectName("target_rssi")
        self.target_rssi_label = QtWidgets.QLabel(self.local)
        self.target_rssi_label.setGeometry(QtCore.QRect(200, 480, 71, 16))
        self.target_rssi_label.setObjectName("target_rssi_label")
        self.hysteresis_rssi = QtWidgets.QComboBox(self.local)
        self.hysteresis_rssi.setGeometry(QtCore.QRect(270, 510, 101, 21))
        self.hysteresis_rssi.setObjectName("hysteresis_rssi")
        self.hysteresis_rssi_label = QtWidgets.QLabel(self.local)
        self.hysteresis_rssi_label.setGeometry(QtCore.QRect(180, 510, 91, 20))
        self.hysteresis_rssi_label.setObjectName("hysteresis_rssi_label")
        self.random_key = QtWidgets.QPushButton(self.local)
        self.random_key.setGeometry(QtCore.QRect(210, 330, 161, 20))
        self.random_key.setObjectName("random_key")
        self.label = QtWidgets.QLabel(self.local)
        self.label.setGeometry(QtCore.QRect(6, 0, 371, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.remote = QtWidgets.QFrame(self.settings)
        self.remote.setEnabled(False)
        self.remote.setGeometry(QtCore.QRect(400, 60, 381, 581))
        self.remote.setStyleSheet("")
        self.remote.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.remote.setFrameShadow(QtWidgets.QFrame.Plain)
        self.remote.setMidLineWidth(1)
        self.remote.setObjectName("remote")
        self.version_label_remote = QtWidgets.QLabel(self.remote)
        self.version_label_remote.setGeometry(QtCore.QRect(10, 40, 41, 16))
        self.version_label_remote.setObjectName("version_label_remote")
        self.radio_version_remote = QtWidgets.QLabel(self.remote)
        self.radio_version_remote.setGeometry(QtCore.QRect(50, 40, 141, 16))
        self.radio_version_remote.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.radio_version_remote.setText("")
        self.radio_version_remote.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.radio_version_remote.setObjectName("radio_version_remote")
        self.board_freq_remote = QtWidgets.QLabel(self.remote)
        self.board_freq_remote.setGeometry(QtCore.QRect(190, 40, 101, 16))
        self.board_freq_remote.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.board_freq_remote.setText("")
        self.board_freq_remote.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.board_freq_remote.setObjectName("board_freq_remote")
        self.device_remote = QtWidgets.QLabel(self.remote)
        self.device_remote.setGeometry(QtCore.QRect(300, 40, 71, 51))
        self.device_remote.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.device_remote.setText("")
        self.device_remote.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.device_remote.setObjectName("device_remote")
        self.rssi_remote = QtWidgets.QLabel(self.remote)
        self.rssi_remote.setGeometry(QtCore.QRect(50, 60, 241, 31))
        self.rssi_remote.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.rssi_remote.setText("")
        self.rssi_remote.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.rssi_remote.setObjectName("rssi_remote")
        self.rssi_label_remote = QtWidgets.QLabel(self.remote)
        self.rssi_label_remote.setGeometry(QtCore.QRect(10, 65, 41, 21))
        self.rssi_label_remote.setObjectName("rssi_label_remote")
        self.format_remote = QtWidgets.QLabel(self.remote)
        self.format_remote.setGeometry(QtCore.QRect(80, 100, 101, 20))
        self.format_remote.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.format_remote.setText("")
        self.format_remote.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.format_remote.setObjectName("format_remote")
        self.format_label_remote = QtWidgets.QLabel(self.remote)
        self.format_label_remote.setGeometry(QtCore.QRect(10, 100, 41, 16))
        self.format_label_remote.setObjectName("format_label_remote")
        self.baud_setting_label_remote = QtWidgets.QLabel(self.remote)
        self.baud_setting_label_remote.setGeometry(QtCore.QRect(10, 130, 41, 16))
        self.baud_setting_label_remote.setObjectName("baud_setting_label_remote")
        self.baud_setting_remote = QtWidgets.QComboBox(self.remote)
        self.baud_setting_remote.setGeometry(QtCore.QRect(80, 130, 101, 21))
        self.baud_setting_remote.setObjectName("baud_setting_remote")
        self.air_speed_remote = QtWidgets.QComboBox(self.remote)
        self.air_speed_remote.setGeometry(QtCore.QRect(80, 160, 101, 21))
        self.air_speed_remote.setObjectName("air_speed_remote")
        self.air_speed_label_remote = QtWidgets.QLabel(self.remote)
        self.air_speed_label_remote.setGeometry(QtCore.QRect(10, 160, 51, 16))
        self.air_speed_label_remote.setObjectName("air_speed_label_remote")
        self.net_id_remote = QtWidgets.QComboBox(self.remote)
        self.net_id_remote.setGeometry(QtCore.QRect(80, 190, 101, 21))
        self.net_id_remote.setObjectName("net_id_remote")
        self.net_id_label_remote = QtWidgets.QLabel(self.remote)
        self.net_id_label_remote.setGeometry(QtCore.QRect(10, 190, 51, 16))
        self.net_id_label_remote.setObjectName("net_id_label_remote")
        self.tx_pwr_remote = QtWidgets.QComboBox(self.remote)
        self.tx_pwr_remote.setGeometry(QtCore.QRect(80, 220, 101, 21))
        self.tx_pwr_remote.setObjectName("tx_pwr_remote")
        self.tx_pwr_label_remote = QtWidgets.QLabel(self.remote)
        self.tx_pwr_label_remote.setGeometry(QtCore.QRect(10, 220, 51, 16))
        self.tx_pwr_label_remote.setObjectName("tx_pwr_label_remote")
        self.ecc_label_remote = QtWidgets.QLabel(self.remote)
        self.ecc_label_remote.setGeometry(QtCore.QRect(10, 250, 61, 16))
        self.ecc_label_remote.setObjectName("ecc_label_remote")
        self.ecc_remote = QtWidgets.QCheckBox(self.remote)
        self.ecc_remote.setGeometry(QtCore.QRect(100, 250, 16, 20))
        self.ecc_remote.setText("")
        self.ecc_remote.setObjectName("ecc_remote")
        self.mavlink_label_remote = QtWidgets.QLabel(self.remote)
        self.mavlink_label_remote.setGeometry(QtCore.QRect(10, 280, 51, 16))
        self.mavlink_label_remote.setObjectName("mavlink_label_remote")
        self.mavlink_remote = QtWidgets.QComboBox(self.remote)
        self.mavlink_remote.setGeometry(QtCore.QRect(80, 280, 101, 21))
        self.mavlink_remote.setObjectName("mavlink_remote")
        self.op_resend_label_remote = QtWidgets.QLabel(self.remote)
        self.op_resend_label_remote.setGeometry(QtCore.QRect(10, 310, 61, 16))
        self.op_resend_label_remote.setObjectName("op_resend_label_remote")
        self.op_resend_remote = QtWidgets.QCheckBox(self.remote)
        self.op_resend_remote.setGeometry(QtCore.QRect(100, 310, 16, 20))
        self.op_resend_remote.setText("")
        self.op_resend_remote.setObjectName("op_resend_remote")
        self.gpi1_1rcin_label_remote = QtWidgets.QLabel(self.remote)
        self.gpi1_1rcin_label_remote.setGeometry(QtCore.QRect(10, 370, 71, 16))
        self.gpi1_1rcin_label_remote.setObjectName("gpi1_1rcin_label_remote")
        self.gpo1_1rcout_label_remote = QtWidgets.QLabel(self.remote)
        self.gpo1_1rcout_label_remote.setGeometry(QtCore.QRect(10, 400, 81, 16))
        self.gpo1_1rcout_label_remote.setObjectName("gpo1_1rcout_label_remote")
        self.min_freq_remote = QtWidgets.QComboBox(self.remote)
        self.min_freq_remote.setGeometry(QtCore.QRect(270, 100, 101, 21))
        self.min_freq_remote.setObjectName("min_freq_remote")
        self.min_freq_label_remote = QtWidgets.QLabel(self.remote)
        self.min_freq_label_remote.setGeometry(QtCore.QRect(200, 100, 51, 16))
        self.min_freq_label_remote.setObjectName("min_freq_label_remote")
        self.max_freq_label_remote = QtWidgets.QLabel(self.remote)
        self.max_freq_label_remote.setGeometry(QtCore.QRect(200, 130, 51, 16))
        self.max_freq_label_remote.setObjectName("max_freq_label_remote")
        self.max_freq_remote = QtWidgets.QComboBox(self.remote)
        self.max_freq_remote.setGeometry(QtCore.QRect(270, 130, 101, 21))
        self.max_freq_remote.setObjectName("max_freq_remote")
        self.num_channels_label_remote = QtWidgets.QLabel(self.remote)
        self.num_channels_label_remote.setGeometry(QtCore.QRect(200, 160, 61, 16))
        self.num_channels_label_remote.setObjectName("num_channels_label_remote")
        self.num_channels_remote = QtWidgets.QComboBox(self.remote)
        self.num_channels_remote.setGeometry(QtCore.QRect(270, 160, 101, 21))
        self.num_channels_remote.setObjectName("num_channels_remote")
        self.duty_cycle_label_remote = QtWidgets.QLabel(self.remote)
        self.duty_cycle_label_remote.setGeometry(QtCore.QRect(200, 190, 61, 16))
        self.duty_cycle_label_remote.setObjectName("duty_cycle_label_remote")
        self.duty_cycle_remote = QtWidgets.QComboBox(self.remote)
        self.duty_cycle_remote.setGeometry(QtCore.QRect(270, 190, 101, 21))
        self.duty_cycle_remote.setObjectName("duty_cycle_remote")
        self.lbt_rssi_label_remote = QtWidgets.QLabel(self.remote)
        self.lbt_rssi_label_remote.setGeometry(QtCore.QRect(200, 220, 61, 16))
        self.lbt_rssi_label_remote.setObjectName("lbt_rssi_label_remote")
        self.lbt_rssi_remote = QtWidgets.QComboBox(self.remote)
        self.lbt_rssi_remote.setGeometry(QtCore.QRect(270, 220, 101, 21))
        self.lbt_rssi_remote.setObjectName("lbt_rssi_remote")
        self.max_window_label_remote = QtWidgets.QLabel(self.remote)
        self.max_window_label_remote.setGeometry(QtCore.QRect(200, 280, 71, 16))
        self.max_window_label_remote.setObjectName("max_window_label_remote")
        self.max_window_remote = QtWidgets.QComboBox(self.remote)
        self.max_window_remote.setGeometry(QtCore.QRect(270, 280, 101, 21))
        self.max_window_remote.setObjectName("max_window_remote")
        self.flow_control_label_remote = QtWidgets.QLabel(self.remote)
        self.flow_control_label_remote.setGeometry(QtCore.QRect(200, 250, 51, 16))
        self.flow_control_label_remote.setObjectName("flow_control_label_remote")
        self.flow_control_remote = QtWidgets.QCheckBox(self.remote)
        self.flow_control_remote.setGeometry(QtCore.QRect(290, 250, 16, 20))
        self.flow_control_remote.setText("")
        self.flow_control_remote.setObjectName("flow_control_remote")
        self.aes_encrypt_label_remote = QtWidgets.QLabel(self.remote)
        self.aes_encrypt_label_remote.setGeometry(QtCore.QRect(200, 310, 81, 16))
        self.aes_encrypt_label_remote.setObjectName("aes_encrypt_label_remote")
        self.aes_encrypt_remote = QtWidgets.QCheckBox(self.remote)
        self.aes_encrypt_remote.setGeometry(QtCore.QRect(290, 310, 16, 20))
        self.aes_encrypt_remote.setText("")
        self.aes_encrypt_remote.setObjectName("aes_encrypt_remote")
        self.aes_key_remote = QtWidgets.QLabel(self.remote)
        self.aes_key_remote.setGeometry(QtCore.QRect(160, 350, 211, 21))
        self.aes_key_remote.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.aes_key_remote.setText("")
        self.aes_key_remote.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextEditable|QtCore.Qt.TextSelectableByMouse)
        self.aes_key_remote.setObjectName("aes_key_remote")
        self.aes_key_label_remote = QtWidgets.QLabel(self.remote)
        self.aes_key_label_remote.setGeometry(QtCore.QRect(160, 330, 51, 16))
        self.aes_key_label_remote.setObjectName("aes_key_label_remote")
        self.standard_mavlink_remote = QtWidgets.QPushButton(self.remote)
        self.standard_mavlink_remote.setGeometry(QtCore.QRect(160, 380, 101, 23))
        self.standard_mavlink_remote.setObjectName("standard_mavlink_remote")
        self.low_latency_remote = QtWidgets.QPushButton(self.remote)
        self.low_latency_remote.setGeometry(QtCore.QRect(270, 380, 101, 23))
        self.low_latency_remote.setObjectName("low_latency_remote")
        self.gpo1_1sbusin_label_remote = QtWidgets.QLabel(self.remote)
        self.gpo1_1sbusin_label_remote.setGeometry(QtCore.QRect(10, 430, 81, 16))
        self.gpo1_1sbusin_label_remote.setObjectName("gpo1_1sbusin_label_remote")
        self.gpo1_3statled_label_remote = QtWidgets.QLabel(self.remote)
        self.gpo1_3statled_label_remote.setGeometry(QtCore.QRect(10, 490, 81, 16))
        self.gpo1_3statled_label_remote.setObjectName("gpo1_3statled_label_remote")
        self.ant_mode_label_remote = QtWidgets.QLabel(self.remote)
        self.ant_mode_label_remote.setGeometry(QtCore.QRect(200, 420, 71, 16))
        self.ant_mode_label_remote.setObjectName("ant_mode_label_remote")
        self.ant_mode_remote = QtWidgets.QComboBox(self.remote)
        self.ant_mode_remote.setGeometry(QtCore.QRect(270, 420, 101, 21))
        self.ant_mode_remote.setObjectName("ant_mode_remote")
        self.gpi1_1rcin_remote = QtWidgets.QRadioButton(self.remote)
        self.gpi1_1rcin_remote.setGeometry(QtCore.QRect(100, 370, 16, 17))
        self.gpi1_1rcin_remote.setText("")
        self.gpi1_1rcin_remote.setObjectName("gpi1_1rcin_remote")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.gpi1_1rcin_remote)
        self.gpo1_1rcout_remote = QtWidgets.QRadioButton(self.remote)
        self.gpo1_1rcout_remote.setGeometry(QtCore.QRect(100, 400, 16, 17))
        self.gpo1_1rcout_remote.setText("")
        self.gpo1_1rcout_remote.setObjectName("gpo1_1rcout_remote")
        self.buttonGroup.addButton(self.gpo1_1rcout_remote)
        self.gpo1_1sbusin_remote = QtWidgets.QRadioButton(self.remote)
        self.gpo1_1sbusin_remote.setGeometry(QtCore.QRect(100, 430, 16, 17))
        self.gpo1_1sbusin_remote.setText("")
        self.gpo1_1sbusin_remote.setObjectName("gpo1_1sbusin_remote")
        self.buttonGroup.addButton(self.gpo1_1sbusin_remote)
        self.gpo1_1sbusout_remote = QtWidgets.QRadioButton(self.remote)
        self.gpo1_1sbusout_remote.setGeometry(QtCore.QRect(100, 460, 16, 17))
        self.gpo1_1sbusout_remote.setText("")
        self.gpo1_1sbusout_remote.setObjectName("gpo1_1sbusout_remote")
        self.buttonGroup.addButton(self.gpo1_1sbusout_remote)
        self.gpo1_3statled_remote = QtWidgets.QRadioButton(self.remote)
        self.gpo1_3statled_remote.setGeometry(QtCore.QRect(100, 490, 16, 17))
        self.gpo1_3statled_remote.setText("")
        self.gpo1_3statled_remote.setObjectName("gpo1_3statled_remote")
        self.buttonGroup.addButton(self.gpo1_3statled_remote)
        self.gpo1_1sbusout_label_remote = QtWidgets.QLabel(self.remote)
        self.gpo1_1sbusout_label_remote.setGeometry(QtCore.QRect(10, 460, 91, 16))
        self.gpo1_1sbusout_label_remote.setObjectName("gpo1_1sbusout_label_remote")
        self.gpio_1_0_nromal_label_remote = QtWidgets.QLabel(self.remote)
        self.gpio_1_0_nromal_label_remote.setGeometry(QtCore.QRect(10, 520, 91, 16))
        self.gpio_1_0_nromal_label_remote.setObjectName("gpio_1_0_nromal_label_remote")
        self.gpio_1_0_nromal_remote = QtWidgets.QRadioButton(self.remote)
        self.gpio_1_0_nromal_remote.setGeometry(QtCore.QRect(100, 520, 16, 17))
        self.gpio_1_0_nromal_remote.setText("")
        self.gpio_1_0_nromal_remote.setChecked(True)
        self.gpio_1_0_nromal_remote.setObjectName("gpio_1_0_nromal_remote")
        self.buttonGroup_3 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_3.setObjectName("buttonGroup_3")
        self.buttonGroup_3.addButton(self.gpio_1_0_nromal_remote)
        self.gpio_1_1_normal_remote = QtWidgets.QRadioButton(self.remote)
        self.gpio_1_1_normal_remote.setGeometry(QtCore.QRect(100, 340, 16, 17))
        self.gpio_1_1_normal_remote.setText("")
        self.gpio_1_1_normal_remote.setChecked(True)
        self.gpio_1_1_normal_remote.setObjectName("gpio_1_1_normal_remote")
        self.buttonGroup.addButton(self.gpio_1_1_normal_remote)
        self.gpio_1_1_normal_label_remote = QtWidgets.QLabel(self.remote)
        self.gpio_1_1_normal_label_remote.setGeometry(QtCore.QRect(10, 340, 91, 16))
        self.gpio_1_1_normal_label_remote.setObjectName("gpio_1_1_normal_label_remote")
        self.gpo1_0_txen485_label_remote = QtWidgets.QLabel(self.remote)
        self.gpo1_0_txen485_label_remote.setGeometry(QtCore.QRect(10, 550, 81, 16))
        self.gpo1_0_txen485_label_remote.setObjectName("gpo1_0_txen485_label_remote")
        self.gpo1_0_txen485_remote = QtWidgets.QRadioButton(self.remote)
        self.gpo1_0_txen485_remote.setGeometry(QtCore.QRect(100, 550, 16, 17))
        self.gpo1_0_txen485_remote.setText("")
        self.gpo1_0_txen485_remote.setObjectName("gpo1_0_txen485_remote")
        self.buttonGroup_3.addButton(self.gpo1_0_txen485_remote)
        self.rate_and_freq_bands_remote = QtWidgets.QComboBox(self.remote)
        self.rate_and_freq_bands_remote.setGeometry(QtCore.QRect(270, 450, 101, 21))
        self.rate_and_freq_bands_remote.setObjectName("rate_and_freq_bands_remote")
        self.rate_and_freq_bands_label_remote = QtWidgets.QLabel(self.remote)
        self.rate_and_freq_bands_label_remote.setGeometry(QtCore.QRect(170, 450, 101, 20))
        self.rate_and_freq_bands_label_remote.setObjectName("rate_and_freq_bands_label_remote")
        self.target_rssi_remote = QtWidgets.QComboBox(self.remote)
        self.target_rssi_remote.setGeometry(QtCore.QRect(270, 480, 101, 21))
        self.target_rssi_remote.setObjectName("target_rssi_remote")
        self.target_rssi_label_remote = QtWidgets.QLabel(self.remote)
        self.target_rssi_label_remote.setGeometry(QtCore.QRect(200, 480, 71, 16))
        self.target_rssi_label_remote.setObjectName("target_rssi_label_remote")
        self.hysteresis_rssi_remote = QtWidgets.QComboBox(self.remote)
        self.hysteresis_rssi_remote.setGeometry(QtCore.QRect(270, 510, 101, 21))
        self.hysteresis_rssi_remote.setObjectName("hysteresis_rssi_remote")
        self.hysteresis_rssi_label_remote = QtWidgets.QLabel(self.remote)
        self.hysteresis_rssi_label_remote.setGeometry(QtCore.QRect(180, 510, 91, 20))
        self.hysteresis_rssi_label_remote.setObjectName("hysteresis_rssi_label_remote")
        self.label_2 = QtWidgets.QLabel(self.remote)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 381, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.save_to_remote = QtWidgets.QCommandLinkButton(self.settings)
        self.save_to_remote.setEnabled(False)
        self.save_to_remote.setGeometry(QtCore.QRect(480, 660, 221, 41))
        self.save_to_remote.setObjectName("save_to_remote")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 811, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.baud_label.setText(_translate("MainWindow", "Baud"))
        self.port_label.setText(_translate("MainWindow", "Port"))
        self.step_1.setText(_translate("MainWindow", "1. Please select the port and baud for your radio"))
        self.step_2.setText(_translate("MainWindow", "2. Click load settings"))
        self.load_settings.setText(_translate("MainWindow", "Load Settings"))
        self.save_settings.setText(_translate("MainWindow", "Save Settings"))
        self.reset_to_defaults.setText(_translate("MainWindow", "Reset to Defaults"))
        self.copy_req_to_remote.setText(_translate("MainWindow", "Copy Requried to Remote"))
        self.version_label.setText(_translate("MainWindow", "Version"))
        self.rssi_label.setText(_translate("MainWindow", "RSSI"))
        self.format_label.setText(_translate("MainWindow", "Format"))
        self.baud_setting_label.setText(_translate("MainWindow", "Baud"))
        self.air_speed_label.setText(_translate("MainWindow", "Air Speed"))
        self.net_id_label.setText(_translate("MainWindow", "Net ID"))
        self.tx_pwr_label.setText(_translate("MainWindow", "TX Power"))
        self.ecc_label.setText(_translate("MainWindow", "ECC"))
        self.mavlink_label.setText(_translate("MainWindow", "Mavlink"))
        self.op_resend_label.setText(_translate("MainWindow", "Op Resend"))
        self.gpi1_1rcin_label.setText(_translate("MainWindow", "GPI1_1R/CIN"))
        self.gpo1_1rcout_label.setText(_translate("MainWindow", "GPO1_1R/COUT"))
        self.min_freq_label.setText(_translate("MainWindow", "Min Freq"))
        self.max_freq_label.setText(_translate("MainWindow", "Max Freq"))
        self.num_channels_label.setText(_translate("MainWindow", "# Channels"))
        self.duty_cycle_label.setText(_translate("MainWindow", "Duty Cycle"))
        self.lbt_rssi_label.setText(_translate("MainWindow", "LBT RSSI"))
        self.max_window_label.setText(_translate("MainWindow", "Max Window"))
        self.flow_control_label.setText(_translate("MainWindow", "RTS CTS"))
        self.aes_encrypt_label.setText(_translate("MainWindow", "AES Encryption"))
        self.aes_key_label.setText(_translate("MainWindow", "AES Key"))
        self.standard_mavlink.setText(_translate("MainWindow", "Standard Mavlink"))
        self.low_latency.setText(_translate("MainWindow", "Low Latency"))
        self.gpo1_1sbusin_label.setText(_translate("MainWindow", "GPO1_1SBUSIN"))
        self.gpo1_3statled_label.setText(_translate("MainWindow", "GPO1_3STATLED"))
        self.ant_mode_label.setText(_translate("MainWindow", "Ant Mode"))
        self.gpo1_1sbusout_label.setText(_translate("MainWindow", "GPO1_1SBUSOUT"))
        self.gpio_1_0_nromal_label.setText(_translate("MainWindow", "GPIO 1.0 Normal"))
        self.gpio_1_1_normal_label.setText(_translate("MainWindow", "GPIO 1.1 Normal"))
        self.gpo1_0_txen485_label.setText(_translate("MainWindow", "GPO1_0TXEN485"))
        self.rate_and_freq_bands_label.setText(_translate("MainWindow", "Rate & Freq Bands"))
        self.target_rssi_label.setText(_translate("MainWindow", "Target RSSI"))
        self.hysteresis_rssi_label.setText(_translate("MainWindow", "Hysteresis RSSI"))
        self.random_key.setText(_translate("MainWindow", "Random Key"))
        self.label.setText(_translate("MainWindow", "Local Modem"))
        self.version_label_remote.setText(_translate("MainWindow", "Version"))
        self.rssi_label_remote.setText(_translate("MainWindow", "RSSI"))
        self.format_label_remote.setText(_translate("MainWindow", "Format"))
        self.baud_setting_label_remote.setText(_translate("MainWindow", "Baud"))
        self.air_speed_label_remote.setText(_translate("MainWindow", "Air Speed"))
        self.net_id_label_remote.setText(_translate("MainWindow", "Net ID"))
        self.tx_pwr_label_remote.setText(_translate("MainWindow", "TX Power"))
        self.ecc_label_remote.setText(_translate("MainWindow", "ECC"))
        self.mavlink_label_remote.setText(_translate("MainWindow", "Mavlink"))
        self.op_resend_label_remote.setText(_translate("MainWindow", "Op Resend"))
        self.gpi1_1rcin_label_remote.setText(_translate("MainWindow", "GPI1_1R/CIN"))
        self.gpo1_1rcout_label_remote.setText(_translate("MainWindow", "GPO1_1R/COUT"))
        self.min_freq_label_remote.setText(_translate("MainWindow", "Min Freq"))
        self.max_freq_label_remote.setText(_translate("MainWindow", "Max Freq"))
        self.num_channels_label_remote.setText(_translate("MainWindow", "# Channels"))
        self.duty_cycle_label_remote.setText(_translate("MainWindow", "Duty Cycle"))
        self.lbt_rssi_label_remote.setText(_translate("MainWindow", "LBT RSSI"))
        self.max_window_label_remote.setText(_translate("MainWindow", "Max Window"))
        self.flow_control_label_remote.setText(_translate("MainWindow", "RTS CTS"))
        self.aes_encrypt_label_remote.setText(_translate("MainWindow", "AES Encryption"))
        self.aes_key_label_remote.setText(_translate("MainWindow", "AES Key"))
        self.standard_mavlink_remote.setText(_translate("MainWindow", "Standard Mavlink"))
        self.low_latency_remote.setText(_translate("MainWindow", "Low Latency"))
        self.gpo1_1sbusin_label_remote.setText(_translate("MainWindow", "GPO1_1SBUSIN"))
        self.gpo1_3statled_label_remote.setText(_translate("MainWindow", "GPO1_3STATLED"))
        self.ant_mode_label_remote.setText(_translate("MainWindow", "Ant Mode"))
        self.gpo1_1sbusout_label_remote.setText(_translate("MainWindow", "GPO1_1SBUSOUT"))
        self.gpio_1_0_nromal_label_remote.setText(_translate("MainWindow", "GPIO 1.0 Normal"))
        self.gpio_1_1_normal_label_remote.setText(_translate("MainWindow", "GPIO 1.1 Normal"))
        self.gpo1_0_txen485_label_remote.setText(_translate("MainWindow", "GPO1_0TXEN485"))
        self.rate_and_freq_bands_label_remote.setText(_translate("MainWindow", "Rate & Freq Bands"))
        self.target_rssi_label_remote.setText(_translate("MainWindow", "Target RSSI"))
        self.hysteresis_rssi_label_remote.setText(_translate("MainWindow", "Hysteresis RSSI"))
        self.label_2.setText(_translate("MainWindow", "Remote Modem"))
        self.save_to_remote.setText(_translate("MainWindow", "Save Remote Settings"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
